### ISSUE TITLE
django.core.context_processors depreceated?

### ISSUE THREAD

**Issue by SamPassmore** [dlce-eva/python-nexus#12]
I am trying to use the Nexus Reader in python 3.7 and i get the message:

```
from django.core.context_processors import csrf
ModuleNotFoundError: No module named 'django.core.context_processors'
```

It looks like context_processors have been moved to django.template.context_processors

https://docs.djangoproject.com/en/1.9/releases/1.8/#django-core-context-processors

I will have a look through the code tomorrow to see if this just requires the name change or somethin more severe.

**Comment by SimonGreenhill** [comment]
Wrong package, think you've installed https://pypi.org/project/nexus/, rather than this thing. Try "pip install python-nexus" rather than 'nexus'?

**Comment by SamPassmore** [comment]
Whoops. Sorry about that. Mostly left this as a note for myself to check in
more detail later. But should've checked more detail first!
