### ISSUE TITLE
Refactor for 2.0

### ISSUE THREAD

**Issue by xrotwang** [dlce-eva/python-nexus#13]
Since the attributes corresponding to blocks are set via `setattr` (see
https://github.com/SimonGreenhill/python-nexus/blob/a090ecf4c2b3fc45b1099ad8cc9058745c9fd418/nexus/reader.py#L45) they cannot be inferred by IDEs, which makes the library harder to use.

It's also a bit more clunky, if not all attributes are set at all times, and `hasattr` must be used when `if reader.trees` should be sufficient (e.g. if the handlers had appropriate `__bool__` methods).

**Comment by SimonGreenhill** [comment]
Ok, so what's the solution here -- set .trees, .data etc in `__init__` to None, and override when present? or make these properties that return None if not found?

(This whole library needs a good refactor :/)

**Comment by xrotwang** [comment]
Ok, I'll take a stab at refactoring :) I guess parsing the `[&R|U]` syntax should live in this library as well, right?

**Comment by SimonGreenhill** [comment]
Much appreciated!

As for [&R], yes in here, or we could make the `newick` library a dependency, and make that able to parse trees in the extended nexus format (incl. name and [&R])?  (i.e. so python-nexus handles nexus parsing, newick does the trees)

**Comment by xrotwang** [comment]
@SimonGreenhill are you ok with re-arranging the source tree, i.e. moving the package to `src`, moving `test` up to the project dir, moving `examples` into `test/fixtures`? Ah, and dropping py2 compat?

**Comment by SimonGreenhill** [comment]
yes, yes, and yes. Let's make it a new  major release though (2.0?)

**Comment by xrotwang** [comment]
What about moving the repos to https://github.com/glottobank (or possibly an org that fits even better - glottobank already has `python-newick`, so that's what may make it suitable)?

**Comment by SimonGreenhill** [comment]
ok --  glottobank? we also have https://github.com/shh-dlce/, but this looks to be largely outdated things?

**Comment by xrotwang** [comment]
ah right. yes, that's better. It's not outdated things only. It also has `appconfig`.

**Comment by xrotwang** [comment]
I'd also rewrite the cli to just provide one `nexus` command with subcommands - as for most of our other packages. Or do you think that's too much of a breaking change?

**Comment by SimonGreenhill** [comment]
Just moved [here](https://github.com/shh-dlce/python-nexus)

**Comment by SimonGreenhill** [comment]
Yes, redoing the cli interface would be really nice too, it's accumulated a lot of cruft. 

I think these can be deleted:

* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_anonymise.py

Related to characters/data:
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_describecharacter.py
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_describetaxa.py
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_nexusmanip.py (everything)
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_randomise.py
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_tally.py

Related to trees:
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_treemanip.py

Perhaps a 'describe' command for:
* nexus_tally
* nexus_describecharacter
* nexus_describetaxa

Perhaps a 'convert' command:
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_multistate2binary.py
* https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexus_to_fasta.py

edit: 
perhaps this https://github.com/shh-dlce/python-nexus/blob/master/nexus/bin/nexuscheck.py can be a 'check' command.

**Comment by xrotwang** [comment]
One more thing: You might want to "release" the association between your personal user with the repos on Zenodo. Then we could hook it up with the institutional one.

**Comment by SimonGreenhill** [comment]
ok, will try that -- once I figure out where to look on zenodo.

**Comment by xrotwang** [comment]
you login with github, and then open the github link from the account drop-down. This will open a list of repos, each with a switch button.

**Comment by xrotwang** [comment]
ah, looks like you don't have to do that. Apparently the association didn't survive the repos move.

**Comment by SimonGreenhill** [comment]
yeah it's not listed in the repos list. Must have been unlinked with the move?

**Comment by xrotwang** [comment]
@SimonGreenhill should we require clldutils?

I'd use clldutils mainly for the cli. So this would pull in some things for no good reason:
https://github.com/clld/clldutils/blob/92ab4cab4f9a39e0d6f20f09ef75e0ea4a11d025/setup.py#L15-L21
But then, once they are there, some may come in handy?

**Comment by SimonGreenhill** [comment]
sure!
