### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by xrotwang** [dlce-eva/python-nexus#14]
I'm somewhat reluctant to break backwards compatibility for stylistic reasons, but `NexusReader.read_string` and `NexusReader.read_file` are just a bit weird, in particular the former, even returning `self`.

I'd say the "real" API should look like this:
```python
class NexusReader:
    def __init__(**blocks):
        self.blocks = {block: self.handlers.get(block, GenericHandler)(lines) for block, lines in blocks.items()}

    @staticmethod
    def iter_blocks(handle):
        ...
        yield block, lines

    @classmethod
    def from_file(cls, filename):
        ...
        return cls(**dict(NexusReader.iter_blocks(handle)))

    @classmethod
    def from_string(cls, strin):
        return cls(...)
```

One could add `read_file` back in, and deprecate it. But would you think that's worth it? I.e. how much code depends on the `NexusReader` API?

**Comment by xrotwang** [comment]
Ok, bolting on the factory method API while keeping the old one isn't too hard. But I'd still deprecrate `read_file` and `read_string`, ok?

**Comment by SimonGreenhill** [comment]
Yes, deprecate. I think most accesses I know of are via `NexusReader(filename)`, and the others (especially `read_string`) were mainly used to make tests better.
