### ISSUE TITLE
loglevel.WARN not handled in `trees` subcommand?

### ISSUE THREAD

**Issue by SimonGreenhill** [dlce-eva/python-nexus#19]
The `trees` command says that to remove logging output (e.g. when piping):

```
To prevent log messages messing up the output, set '--log-level=WARN'.
```

... but this doesn't work i.e parser needs to have log-level added. I'm not sure the best way to do this? 

Also, there's a --quiet flag:

```
    parser.add_argument(
        "-q", "--quiet", dest="quiet",
        action="store_true", default=False,
        help="Be quiet (no logging information displayed)")
```

...which looks like it doesn't work. We should use either --log-level or -q, preference?

**Comment by xrotwang** [comment]
`--log-level=WARNING` works for me. When I redirect `stdout` to a file, the log message at `stderr` appears/disappears as expected:
```
$ nexus trees -n 1 tests/examples/example-beast.trees > out_unfiltered.txt
INFO    1 trees found with 38 translated taxa
$ nexus --log-level=WARNING trees -n 1 tests/examples/example-beast.trees > out_filtered.txt
```

**Comment by SimonGreenhill** [comment]
...ahh, that works but if it's before `trees`, `nexus  trees --log-level=WARNING ...etc` doesn't work. This looks like a wontfix?

**Comment by xrotwang** [comment]
Yes, but putting in **after** the subcommand should at least result in an error, no?

I agree that it's a bit complex to have options on **both** main- and subcommand. But it also makes sense, I think.

**Comment by xrotwang** [comment]
So having the more generic `--log-level` as option for **all** commands, I'd just remove `--quiet`.

**Comment by SimonGreenhill** [comment]
yeah that makes sense, as does removing -q
