### ISSUE TITLE
Support for non-interleaved Nexus format?

### ISSUE THREAD

**Issue by mvences** [dlce-eva/python-nexus#21]
Dear python-nexus developers, 
we are currently trying to use your Nexus parser in a set of tools for biological taxonomy and phylogenetic analysis (to be published in the next months). We also developed an own simple nexus parser, but it would be preferable to use your dedicated tool which offers extended features. 
We noticed that apparently python-nexus does not support simple non-interleaved Nexus files. Could you check and maybe implement this in the next version? This concerns files such as the example appended here.
Thanks a lot and kind regards, 
Miguel

[Nexusexample_noninterleaved.NEX.txt](https://github.com/dlce-eva/python-nexus/files/5835670/Nexusexample_noninterleaved.NEX.txt)

**Comment by xrotwang** [comment]
I'll look into this! Having wider applicability would definitly benefit the maintenance prospects of our tool.

**Comment by xrotwang** [comment]
@mvences as far as I can tell, the problem, `python-nexus` is having with your file, is **not** about interleaved or not, but that lines in the file are wrapped at 100 chars. May this be due to any previous processing?

**Comment by mvences** [comment]
Thanks for the superfast response!

I see. Good point. But this is a quite common situation in DNA sequences (having them in this "wrapped" format). Most phylogeny programs can read such files without any trouble (MrBayes, Paup....). So, it might be a good idea to enable python-nexus to read them as well. I am myself not a programmer, so I can also explain in a very naive way: The reader should "understand" that this is not interleaved, so it should expect in the matrix block the first line representing a sample name (not interrupted by line breaks!) and in all subsequent lines (interrupted or not by line breaks or spaces which should be just ignored) the characters (up to the total given in "nchar"). And then the next line again would represent the second sample name ....

**Comment by xrotwang** [comment]
ah, ok, I see. So basically, whitespace is only significant between taxon name and chars, and otherwise it's "read until nchar".

**Comment by mvences** [comment]
Yes, I think that's the point. The problem is there are so many different ways to provide information of DNA sequences ... and programmers of phylogeny tools probably have worked hard to make their Nexus readers as "bullet-proof" as possible against all the possible weird things users could do to their matrices...
Me as a user (for over 25 years now) of these programs have never appreciated the amount of work that is needed to get them to run smoothly and to seal them against all the strange stuff users could do with input files...

**Comment by xrotwang** [comment]
@mvences I just released [python-nexus 2.1](https://pypi.org/project/python-nexus/) which includes a fix for this issue. Please, let us know if the new version works for you.
