### ISSUE TITLE
nexus trees -n should accept a random seed option

### ISSUE THREAD

**Issue by xrotwang** [dlce-eva/python-nexus#24]
To allow for reproducible sampling, `nexus trees -n` should allow setting the random seed, e.g. via
https://github.com/clld/clldutils/blob/1cf87e69b3696604ea2283dc9fee876d06b05910/src/clldutils/clilib.py#L292-L299

**Comment by xrotwang** [comment]
@SimonGreenhill I'd guess this would be useful in the context of phlorest, right?

**Comment by SimonGreenhill** [comment]
sounds good

**Comment by xrotwang** [comment]
Turns out python-nexus fails with python-newick 1.3. BEAST node annotations seem to be different from other programs'.
