### ISSUE TITLE
Loading of Nexus files fails at attempting to decode `utf-8` data

### ISSUE THREAD

**Issue by codedump** [dlce-eva/python-nexus#36]
Hello,

trying to load a specific Nexus file (in my case one that was generated with the [spec2nexus utility](https://github.com/prjemian/spec2nexus)) fails like this:
```
$ nexus describetexa example.hdf5
Traceback (most recent call last):
  File "/usr/local/bin/nexus", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/nexus/__main__.py", line 26, in main
    return args.main(args) or 0
  File "/usr/local/lib/python3.10/site-packages/nexus/commands/describetaxa.py", line 17, in run
    nexus_obj = get_reader(args, required_blocks=['data'])
  File "/usr/local/lib/python3.10/site-packages/nexus/cli_util.py", line 64, in get_reader
    res.append(NexusReader.from_file(f))
  File "/usr/local/lib/python3.10/site-packages/nexus/reader.py", line 54, in from_file
    res._set_blocks(NexusReader._blocks_from_file(filename, encoding=encoding))
  File "/usr/local/lib/python3.10/site-packages/nexus/reader.py", line 157, in _blocks_from_file
    res = NexusReader._iter_blocks(handle.readlines())
  File "/usr/lib64/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib64/python3.10/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

How to reproduce:
1. Download the [example file](https://cloud.udkm.physik.uni-potsdam.de/s/cM54L6zKz5K7ksG) before the link expires (2022-10-19), password is `jinkiesAndScooby`
2. Execute a python-nexus command that requires opening the file, e.g. `nexus describetaxa` from the command line, current `pip install` version
3. Watch the fail :-)

What happens: see above.

What should happen instead: not crash; either print out a common error (e.g. if Nexus file is corrupt), or print Nexus file information (Nexus file being most likely valid).

What I believe the reason is: the HDF5 is a binary format (right?), but the line quoted in the error message (157 in file reader.py) attempts to open the HDF5 file as a text file, and to decode it as a specific `utf-8` variant. Obviously, at a specific point it fails. I'm not sure whether it's "byte 0" in the file, or just "byte 0" with relation to some arbitrary `handle.readnlines()` internals, e.g. a newline character within the HDF5 file.

Fix is probably to *not* open the HDF5 file as text, but as binary. But I don't have a general insight over what this entails, given that the whole reading routine is apparently built around a `utf-8` conversion of the data stream early on.

Thanks & Cheers,
F.

**Comment by xrotwang** [comment]
Hm. I'm a bit at a loss here. What does "Nexus HDF5 file" mean? Each Nexus block is written as HDF5 group? So, Nexus is regarded as an abstract data model and HDF5 is used to write data conforming to this model to disk?
If so, then I guess `python-nexus` is not likely to support reading such files. I'd say - if anything - Nexus is a spec for "data in text files", and somewhat ill-defined for that. Many different "Nexus blocks" are simply defined by a (single?) software package that understands them. So I can't see Nexus becoming a proper data model.

**Comment by codedump** [comment]
I'm new to the whole "Nexus as a scientific file format" business, but literally the 1st Python code example I saw over at [nexusformat.org](https://manual.nexusformat.org/introduction.html) was Nexus encapsulated in a HDF5 file.

I assumed this procedure is somehow the "standard way of doing stuff", or at least: "preferred way?" ¯\\_ (ツ)_/¯

(I may be mistaken, but I think I rember having read in the specs that HDF5 is the preferred on-disk container for Nexus data?...)

I assumed `python-nexus` was doing exactly this and tried to open a Nexus-conformant HDF5 file using this package, and it failed. Not to get into discussions about the merits and shortcomings of HDF5, but as far as I understood the Nexus specs, this is pretty much what it serves with respect to HDF5: standardize on a way to store data such that any tool that understands Nexus knows where to find the data within a HDF container.

But if you're not using HDF5, then I guess my bug report is moot. May I ask what on-disk format are you using?

F.

**Comment by SimonGreenhill** [comment]
Hi, I think you're looking at a different format and type of data. The nexus format this library handles is for bioinformatics [see here](https://en.wikipedia.org/wiki/Nexus_file) while the NeXus you're after is for physics data. I think you'll have more luck with an HDF5 library e.g. https://www.h5py.org/

**Comment by codedump** [comment]
Sounds like it. I wasn't aware there were more of Nexus...

May I suggest dropping a hint in the introduction section of the README?

In any case, thanks for clarification.

**Comment by SimonGreenhill** [comment]
Good idea -- I've made [these changes](https://github.com/dlce-eva/python-nexus/commit/43f3973e65e26b30f9c694e5cdcf47894bacc0a6) which should help
