### ISSUE TITLE
Parsing trees?

### ISSUE THREAD

**Issue by tresoldi** [dlce-eva/python-nexus#7]
I wrote a small stack-based parser for reading my trees, maybe you want to use it:

def parse_tree(tree_source):
    stack = []
    for i, c in enumerate(tree_source):
        if c == '(':
            stack.append(i)
        elif c == ')' and stack:
            start = stack.pop()
            yield (len(stack), tree_source[start + 1: i])

s = '((1,((22,23),((((27,(34,7)),((5,38),31)),(35,33)),4))),(((9,(25,(26,21))),(39,17)),((((11,(((10,15),14),(((12,18),24),(37,8)))),(30,(32,((13,29),(20,((28,36),6)))))),(19,(40,3))),(16,2))))'
print(list(parse_tree(s)))

**Comment by SimonGreenhill** [comment]
closing in favor of #16 :)
